apiVersion: batch/v1
kind: CronJob
metadata:
  name: cve-auto-mail
spec:
  schedule: "35 17 * * *"  # Chạy hàng ngày lúc 17:20 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cve-auto-mail
            image: cve-auto-mail:latest
            imagePullPolicy: IfNotPresent
            env:
              - name: GMAIL_USER
                value: "automationmailvtb@gmail.com"
              - name: GMAIL_PASSWORD
                value: "cuuy ephf bxzu bjvi"
              - name: RECIPIENTS
                value: "hoangthaifc01@gmail.com,ldhoang@vietinbank.vn"
            resources:
              limits:
                memory: "256Mi"
                cpu: "500m"
          restartPolicy: OnFailure
